// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CronJob is an autogenerated mock type for the CronJob type
type CronJob struct {
	mock.Mock
}

// GetCron provides a mock function with given fields:
func (_m *CronJob) GetCron() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *CronJob) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *CronJob) Run() {
	_m.Called()
}

type mockConstructorTestingTNewCronJob interface {
	mock.TestingT
	Cleanup(func())
}

// NewCronJob creates a new instance of CronJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCronJob(t mockConstructorTestingTNewCronJob) *CronJob {
	mock := &CronJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
