// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	configs "news-hub-microservices_news-api/configs"

	mock "github.com/stretchr/testify/mock"
)

// JobsFactory is an autogenerated mock type for the JobsFactory type
type JobsFactory struct {
	mock.Mock
}

// RunAll provides a mock function with given fields: config
func (_m *JobsFactory) RunAll(config configs.Config) {
	_m.Called(config)
}

type mockConstructorTestingTNewJobsFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobsFactory creates a new instance of JobsFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobsFactory(t mockConstructorTestingTNewJobsFactory) *JobsFactory {
	mock := &JobsFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
