// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	clients "news-hub-microservices_news-api/internal/clients"
	controllers "news-hub-microservices_news-api/internal/controllers"

	mock "github.com/stretchr/testify/mock"

	services "news-hub-microservices_news-api/internal/services"
)

// LayersFactory is an autogenerated mock type for the LayersFactory type
type LayersFactory struct {
	mock.Mock
}

// GetHealthChecksController provides a mock function with given fields:
func (_m *LayersFactory) GetHealthChecksController() controllers.HealthChecksController {
	ret := _m.Called()

	var r0 controllers.HealthChecksController
	if rf, ok := ret.Get(0).(func() controllers.HealthChecksController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(controllers.HealthChecksController)
		}
	}

	return r0
}

// GetNewsController provides a mock function with given fields:
func (_m *LayersFactory) GetNewsController() controllers.NewsController {
	ret := _m.Called()

	var r0 controllers.NewsController
	if rf, ok := ret.Get(0).(func() controllers.NewsController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(controllers.NewsController)
		}
	}

	return r0
}

// GetNewsService provides a mock function with given fields:
func (_m *LayersFactory) GetNewsService() services.NewsService {
	ret := _m.Called()

	var r0 services.NewsService
	if rf, ok := ret.Get(0).(func() services.NewsService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.NewsService)
		}
	}

	return r0
}

// GetUsersApiClient provides a mock function with given fields:
func (_m *LayersFactory) GetUsersApiClient() clients.UsersApiClient {
	ret := _m.Called()

	var r0 clients.UsersApiClient
	if rf, ok := ret.Get(0).(func() clients.UsersApiClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clients.UsersApiClient)
		}
	}

	return r0
}

type mockConstructorTestingTNewLayersFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewLayersFactory creates a new instance of LayersFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLayersFactory(t mockConstructorTestingTNewLayersFactory) *LayersFactory {
	mock := &LayersFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
