// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "news-hub-microservices_news-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// NewsRepository is an autogenerated mock type for the NewsRepository type
type NewsRepository struct {
	mock.Mock
}

// AddNewsReader provides a mock function with given fields: reader
func (_m *NewsRepository) AddNewsReader(reader *models.NewsReader) {
	_m.Called(reader)
}

// CreateBulk provides a mock function with given fields: newsList
func (_m *NewsRepository) CreateBulk(newsList []models.News) {
	_m.Called(newsList)
}

// FindAll provides a mock function with given fields: offset, limit, userId
func (_m *NewsRepository) FindAll(offset int, limit int, userId *uuid.UUID) *[]models.News {
	ret := _m.Called(offset, limit, userId)

	var r0 *[]models.News
	if rf, ok := ret.Get(0).(func(int, int, *uuid.UUID) *[]models.News); ok {
		r0 = rf(offset, limit, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.News)
		}
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *NewsRepository) FindById(id string) *models.News {
	ret := _m.Called(id)

	var r0 *models.News
	if rf, ok := ret.Get(0).(func(string) *models.News); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.News)
		}
	}

	return r0
}

// GetTotal provides a mock function with given fields:
func (_m *NewsRepository) GetTotal() *int64 {
	ret := _m.Called()

	var r0 *int64
	if rf, ok := ret.Get(0).(func() *int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	return r0
}

type mockConstructorTestingTNewNewsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewsRepository creates a new instance of NewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewsRepository(t mockConstructorTestingTNewNewsRepository) *NewsRepository {
	mock := &NewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
