// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "news-hub-microservices_news-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewsRepository is an autogenerated mock type for the NewsRepository type
type NewsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *NewsRepository) Create(user *models.News) {
	_m.Called(user)
}

type mockConstructorTestingTNewNewsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewsRepository creates a new instance of NewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewsRepository(t mockConstructorTestingTNewNewsRepository) *NewsRepository {
	mock := &NewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
