// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	clients "news-hub-microservices_news-api/internal/clients"

	mock "github.com/stretchr/testify/mock"
)

// NewsProxyApiClient is an autogenerated mock type for the NewsProxyApiClient type
type NewsProxyApiClient struct {
	mock.Mock
}

// GetChannelLatestNews provides a mock function with given fields: channel
func (_m *NewsProxyApiClient) GetChannelLatestNews(channel string) clients.GetChannelLatestNewsResponse {
	ret := _m.Called(channel)

	var r0 clients.GetChannelLatestNewsResponse
	if rf, ok := ret.Get(0).(func(string) clients.GetChannelLatestNewsResponse); ok {
		r0 = rf(channel)
	} else {
		r0 = ret.Get(0).(clients.GetChannelLatestNewsResponse)
	}

	return r0
}

// GetChannelsNames provides a mock function with given fields:
func (_m *NewsProxyApiClient) GetChannelsNames() clients.GetChannelsNamesResponse {
	ret := _m.Called()

	var r0 clients.GetChannelsNamesResponse
	if rf, ok := ret.Get(0).(func() clients.GetChannelsNamesResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(clients.GetChannelsNamesResponse)
	}

	return r0
}

type mockConstructorTestingTNewNewsProxyApiClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewsProxyApiClient creates a new instance of NewsProxyApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewsProxyApiClient(t mockConstructorTestingTNewNewsProxyApiClient) *NewsProxyApiClient {
	mock := &NewsProxyApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
