// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewsService is an autogenerated mock type for the NewsService type
type NewsService struct {
	mock.Mock
}

// FetchNews provides a mock function with given fields:
func (_m *NewsService) FetchNews() {
	_m.Called()
}

type mockConstructorTestingTNewNewsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewsService creates a new instance of NewsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewsService(t mockConstructorTestingTNewNewsService) *NewsService {
	mock := &NewsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
